### ISSUE TITLE
ci: add go build cache for docker

### ISSUE THREAD

**Issue by xendarboh** [0KnowledgeNetwork/opt#78]
```yaml
# https://docs.docker.com/build/ci/github-actions/cache/#cache-mounts
- name: Go Build Cache for Docker
  uses: actions/cache@v4
  with:
    path: go-build-cache
    key: ${{ runner.os }}-go-build-cache-${{ hashFiles('**/go.sum') }}
- name: inject go-build-cache into docker
  uses: reproducible-containers/buildkit-cache-dance@4b2444fec0c0fb9dbf175a96c094720a692ef810 # v2.1.4
  with:
    cache-source: go-build-cache

```
