### ISSUE TITLE
fix(walletshield): Unix socket file is not cleaned up after process termination

### ISSUE THREAD

**Issue by xendarboh** [0KnowledgeNetwork/opt#85]
When the client is configured to use a Unix socket, the walletshield application fails to clean up the socket file, resulting in an error on subsequent executions unless the file is manually removed.  

**Configuration:**  
```toml
ListenNetwork = "unix"                                                                                                                                                                                                                                           
ListenAddress = "/tmp/client2.sock"
```

**Error:**  
```
panic: listen unix /tmp/client2.sock: bind: address already in use

goroutine 1 [running]:
main.main()
        tmp-goreleaser/apps/walletshield/main.go:123 +0x805
```

This prevents the application from starting again without manual intervention.
